function [fitresult, gof] = createFit(XX, YY)
%CREATEFIT(XX,YY)
%  Create a fit.
%
%  Data for 'NPPTvIFE' fit:
%      X Input : XX
%      Y Output: YY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Feb-2022 17:10:20


%% Fit: 'NPPTvIFE'.
[xData, yData] = prepareCurveData( XX, YY );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [7312399.80641618 5.12513213961715];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'NPPTvIFE' );
h = plot( fitresult, xData, yData );
legend( h, 'YY vs. XX', 'NPPTvIFE', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX', 'Interpreter', 'none' );
ylabel( 'YY', 'Interpreter', 'none' );
grid on


